name: countries_listview
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - lib/images/daylily-flower-and-buds-blur2.jpg
  - lib/images/photouno.jpg
  - lib/images/laptops.jpg
  - lib/images/smartphones.jpg
  - lib/images/television.jpg
  - lib/images/tablets.jpg
  uses-material-design: true
